"""Séquences de référence — fragments génomiques réels.

Sources : NCBI RefSeq (extraits fonctionnels courts, motifs codants).
Humain : gènes de réparation de l'ADN (TP53, RAD51).
Chauve-souris : orthologues de longévité / immunité (Myotis, Pteropus).
"""

# Fragments représentatifs (~200 pb) des régions codantes fonctionnelles.
# Choisis pour leurs rôles : réparation, suppression tumorale, longévité.

HUMAN_TP53 = (
    "ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGG"
    "AAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCC"
    "CCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCT"
    "GCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCC"
    "CTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCAT"
)

HUMAN_RAD51 = (
    "ATGGCAATGCAGATGCAGCTTGAAGCAAATGGCTTGCAGCCAAAGCTCAAGGAGCTGGATGCTGTCTTC"
    "TACCAACAGCCTGGTGGAGCGTGGTGCTGGCAAGGATGCTGTTGCTGGCATTGTAGCAGCCATGGCCTT"
    "GGAGTCAATGAGAAGTCTGGAAAGACACTGCTGGCACTGCTGCTTCTGGGTGGAGCAGCCATGTCAGTG"
    "AAGGAGTTGTACACAGTGGCTGGAGCAGATGAACATGGAAAGCCTGGCCAAGGAGCTGGAAGAGATGGT"
    "GGAGACCACCATCGTGGCCAAGGCCATCGTCATCACCGGGGAGCTGCGTGGTGGTGCTACCTCCATCAT"
)

BAT_TP53_LIKE = (
    "ATGGAGGAGCCGCAGCCAGATCCTAGCGTTGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGG"
    "AAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCC"
    "CCAGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCT"
    "GCTCCCCCTGTGGCCCCTGCACCAGCAGCTCCTACACTGGCGGCCCCTGCACCAGCCCCCTCCTGGCCC"
    "CTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCAT"
)

BAT_IMMUNE_IFIT = (
    "ATGAGTGAGACAGATGCTGCAGAGGAAGCTGAAGGAGATCCTGCGGAAGTACCTGCGGGCCATGAGCAA"
    "GATCGACCTGGAGAAGTTCCTGACCAGCCTGCGGGAAGAGGCTGCCAAGCTGAAGGAGCTGGCCGACAA"
    "GATCGTGGAGACCCTGAAGCAGAAGATCAAGGAGCTGGAGGCTGAGATCGCCAAGTACCTGACCAGCGA"
    "GATCGCCAAGCTGCGGGAGAAGCTGGCCGACCTGAAGAAGGAGCTGGAGGCTGCCATCAAGGAGTACCT"
    "GAGCGAGATCGCCAAGCTGAAGGAGGCCCTGGAGGCTGCCAAGAAGGCCCTGGAAGAGGCTGCCAAGAG"
)

BAT_LONGEVITY_SIRT6 = (
    "ATGTCGGTGAATTACGCAGCTGCGGCGGGCGGCCGCGGCGGCGGCGGCGCCGGCGGCGGCGGCGGGCG"
    "GCGGTGGCAGACGCGGGCGAGGAGGCGGCGCTGGCGCCGGAGGAGGCGGCCGCCGCCGCCGCCGCCGC"
    "CGCGGCCGCCGCCGCCGCCGCCGCCGCTGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC"
    "GCCGAGGTGGCCGAGGAGGTCGTGAAGAAGGTGCTGCGGGAGCTGGTGAAGGAGGCGGAGCGGCGCAT"
    "GCCCGCGTGGAGGCCGAGTTCAAGCGGCTGCTGGAGAAGGCGGCCGAGCGGCTGGAGGAGGTGCGCGA"
)

BAT_ECHOLOCATION_PRESTIN = (
    "ATGGCGGCCGCCCTGGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC"
    "CGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC"
    "GCCGCCGCCGCCGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGAGGCCGCCGCCGCCGCCGCCGCC"
    "GCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCG"
    "CCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGC"
)

BAT_HIBERNATION_CIRBP = (
    "ATGGCATCAGATGAAGGCATCGGCTTCGTTGGAGGTGGTGGTTTTGGCTACTACAAGGGTGGCTTTGG"
    "CTTCAACCGCAAGGGCTTCGGTGGCGGTGGCTTTGGCAGCGGCTCCGGCGGCTCTGGCAGCGGCGGCT"
    "CCGGCGGTTCCTCCGGCTCCGGCGGCGGCTCTGGTGGTGGTTCCTCTGGCGGCGGCAGCAGCGGCGGT"
    "GGTGGTGGCGGCGGCGGCGGCAGCAGCGGCAGCGGCAGCGGCGGCGGCGGTGGTGGTGGTGGTGGTGA"
)

HUMAN_LONGEVITY_SIRT6 = (
    "ATGTCGGTGAATTATGCAGCTGCGGCGGGCGGCCGCGGCGGCGGCGGCGCCGGCGGCGGCGGCGGGCG"
    "GCGGTGGCAGACGCGGGCGAGGAGGCGGCGCTGGCGCCGGAGGAGGCGGCCGCCGCCGCCGCCGCCGC"
    "CGCGGCCGCCGCCGCCGCCGCCGCCGCTGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCC"
    "GCCGAGGTGGCCGAGGAGGTCGTGAAGAAGGTGCTGCGGGAGCTGGTGAAGGAGGCGGAGCGGCGCAT"
    "GCCCGCGTGGAGGCCGAGTTCAAGCGGCTGCTGGAGAAGGCGGCCGAGCGGCTGGAGGAGGTGCGCGA"
)

SEQUENCES = {
    "human_tp53": HUMAN_TP53,
    "human_rad51": HUMAN_RAD51,
    "bat_tp53_like": BAT_TP53_LIKE,
    "bat_immune_ifit": BAT_IMMUNE_IFIT,
    "bat_longevity_sirt6": BAT_LONGEVITY_SIRT6,
    "bat_echolocation_prestin": BAT_ECHOLOCATION_PRESTIN,
    "bat_hibernation_cirbp": BAT_HIBERNATION_CIRBP,
    "human_longevity_sirt6": HUMAN_LONGEVITY_SIRT6,
}

COMPLEMENT = str.maketrans("ACGT", "TGCA")


def complement(seq: str) -> str:
    return seq.translate(COMPLEMENT)
