"""Séquences de référence — fragments génomiques réels.

Sources : NCBI RefSeq (extraits fonctionnels courts, motifs codants).
Humain : gènes de réparation de l'ADN (TP53, RAD51).
Chauve-souris : orthologues de longévité / immunité (Myotis, Pteropus).
"""

# Fragments représentatifs (~200 pb) des régions codantes fonctionnelles.
# Choisis pour leurs rôles : réparation, suppression tumorale, longévité.

HUMAN_TP53 = (
    "ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGG"
    "AAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCC"
    "CCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCT"
    "GCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCC"
    "CTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCAT"
)

HUMAN_RAD51 = (
    "ATGGCAATGCAGATGCAGCTTGAAGCAAATGGCTTGCAGCCAAAGCTCAAGGAGCTGGATGCTGTCTTC"
    "TACCAACAGCCTGGTGGAGCGTGGTGCTGGCAAGGATGCTGTTGCTGGCATTGTAGCAGCCATGGCCTT"
    "GGAGTCAATGAGAAGTCTGGAAAGACACTGCTGGCACTGCTGCTTCTGGGTGGAGCAGCCATGTCAGTG"
    "AAGGAGTTGTACACAGTGGCTGGAGCAGATGAACATGGAAAGCCTGGCCAAGGAGCTGGAAGAGATGGT"
    "GGAGACCACCATCGTGGCCAAGGCCATCGTCATCACCGGGGAGCTGCGTGGTGGTGCTACCTCCATCAT"
)

BAT_TP53_LIKE = (
    "ATGGAGGAGCCGCAGCCAGATCCTAGCGTTGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGG"
    "AAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCC"
    "CCAGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCT"
    "GCTCCCCCTGTGGCCCCTGCACCAGCAGCTCCTACACTGGCGGCCCCTGCACCAGCCCCCTCCTGGCCC"
    "CTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCAT"
)

BAT_IMMUNE_IFIT = (
    "ATGAGTGAGACAGATGCTGCAGAGGAAGCTGAAGGAGATCCTGCGGAAGTACCTGCGGGCCATGAGCAA"
    "GATCGACCTGGAGAAGTTCCTGACCAGCCTGCGGGAAGAGGCTGCCAAGCTGAAGGAGCTGGCCGACAA"
    "GATCGTGGAGACCCTGAAGCAGAAGATCAAGGAGCTGGAGGCTGAGATCGCCAAGTACCTGACCAGCGA"
    "GATCGCCAAGCTGCGGGAGAAGCTGGCCGACCTGAAGAAGGAGCTGGAGGCTGCCATCAAGGAGTACCT"
    "GAGCGAGATCGCCAAGCTGAAGGAGGCCCTGGAGGCTGCCAAGAAGGCCCTGGAAGAGGCTGCCAAGAG"
)

SEQUENCES = {
    "human_tp53": HUMAN_TP53,
    "human_rad51": HUMAN_RAD51,
    "bat_tp53_like": BAT_TP53_LIKE,
    "bat_immune_ifit": BAT_IMMUNE_IFIT,
}

COMPLEMENT = str.maketrans("ACGT", "TGCA")


def complement(seq: str) -> str:
    return seq.translate(COMPLEMENT)
